# Generated by Django 4.1.5 on 2023-05-22 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('India', '0004_remove_post_community_remove_post_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postpic', models.ImageField(blank=True, upload_to='')),
                ('status', models.TextField()),
                ('likes', models.IntegerField()),
                ('community', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='India.map')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='India.member')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='community.post')),
            ],
        ),
    ]
