# Generated by Django 4.2.1 on 2023-05-27 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('India', '0004_remove_post_community_remove_post_user_and_more'),
        ('community', '0002_comment_commenter_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='specpost', to='community.post')),
                ('user', models.ManyToManyField(blank=True, related_name='likers', to='India.member')),
            ],
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='speccomment', to='community.comment')),
                ('user', models.ManyToManyField(blank=True, related_name='commentliker', to='India.member')),
            ],
        ),
    ]
