# Generated by Django 4.2.1 on 2023-05-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_comment_likes_postlikes_commentlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlikes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlikes',
            name='user',
        ),
        migrations.DeleteModel(
            name='CommentLikes',
        ),
        migrations.DeleteModel(
            name='PostLikes',
        ),
    ]
