# Generated by Django 4.2.1 on 2023-05-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_postlikes_post_remove_postlikes_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
