# Generated by Django 4.2.1 on 2023-05-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('India', '0004_remove_post_community_remove_post_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
